# Generated by Django 4.2.7 on 2025-11-30 12:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_add_ab_person_id'),
        ('campaigns', '0017_add_manager_to_campaign_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_address', models.CharField(db_index=True, help_text="Base address without apartment number, e.g. 'Hausmanns gate 19A, 0182 Oslo'", max_length=500)),
                ('position', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location of the building (from first address)', srid=4326)),
                ('total_units', models.IntegerField(default=0, help_text='Total number of apartments in this building')),
                ('visited_units', models.IntegerField(default=0, help_text='Number of apartments that have been visited (status not null)')),
                ('status', models.CharField(choices=[('unvisited', 'Unvisited'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='unvisited', help_text='Computed status: unvisited (grey), in_progress (yellow), completed (blue)', max_length=20)),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text='True when all apartments have been visited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this building belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, help_text='Manager who first discovered this building', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buildings', to='users.manager')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'building',
                'ordering': ['base_address'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='idx_bldg_campaign_status'), models.Index(fields=['is_completed'], name='idx_bldg_completed')],
                'unique_together': {('base_address', 'campaign')},
            },
        ),
    ]
