# Generated by Django 4.2.7 on 2025-12-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_ab_person_id'),
        ('buildings', '0001_initial_building_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, help_text='Employee who first discovered this building (if not created by manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buildings', to='users.employee'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['created_by'], name='idx_bldg_created_by'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['created_by_employee'], name='idx_bldg_created_by_emp'),
        ),
    ]
