# Generated by Django 4.2.7 on 2025-11-20 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0017_add_manager_to_campaign_employee'),
        ('addresses', '0007_alter_address_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_address', models.TextField(help_text="Base address without apartment number, e.g. 'Hausmanns gate 19A, 0182 Oslo'")),
                ('apartment_number', models.CharField(help_text="Apartment/unit number, e.g. '1', '2A', 'H0102'", max_length=50)),
                ('status', models.CharField(blank=True, choices=[('ja', 'Ja'), ('nei', 'Nei'), ('ikke_hjemme', 'Ikke hjemme'), ('folg_opp', 'Følg opp')], help_text='NULL if never visited, otherwise matches address status', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, help_text='Address record created when this apartment was visited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_record', to='addresses.address')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this apartment catalogue belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'db_table': 'apartment',
                'ordering': ['base_address', 'apartment_number'],
                'indexes': [models.Index(fields=['base_address'], name='idx_apt_base_addr'), models.Index(fields=['campaign', 'base_address'], name='idx_apt_campaign_base'), models.Index(fields=['status'], name='idx_apt_status')],
                'unique_together': {('base_address', 'apartment_number')},
            },
        ),
    ]
