# Generated by Django 4.2.7 on 2025-11-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial_building_model'),
        ('campaigns', '0017_add_manager_to_campaign_employee'),
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Building this apartment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='base_address',
            field=models.TextField(blank=True, help_text='DEPRECATED - Use building.base_address instead', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED - Use building.campaign instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='campaigns.campaign'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['building'], name='idx_apt_building'),
        ),
    ]
