# Generated by Django 4.2.7 on 2025-07-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_employees', to='campaigns.campaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='users.employee')),
            ],
            options={
                'verbose_name': 'Campaign Employee',
                'verbose_name_plural': 'Campaign Employees',
                'db_table': 'campaign_employee',
                'unique_together': {('campaign', 'employee')},
            },
        ),
    ]
