# Generated by Django 4.2.7 on 2025-07-20 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignForm',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not Done')], default='not_done', help_text='Form completion status', max_length=10)),
                ('sales_rep_id', models.UUIDField(help_text='ID of the manager or employee who submitted the form')),
                ('first_name', models.CharField(help_text='First name of the person', max_length=255)),
                ('last_name', models.CharField(help_text='Last name of the person', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('sms_phone_number', models.CharField(help_text='SMS phone number', max_length=20)),
                ('kidnumber', models.CharField(blank=True, help_text='KID number (can be null)', max_length=50, null=True)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('address', models.CharField(help_text='Street address', max_length=500)),
                ('postnummer', models.CharField(help_text='Postal code', max_length=10)),
                ('posted', models.CharField(help_text='City/Postal area', max_length=255)),
                ('kontonummer', models.CharField(help_text='Account number', max_length=50)),
                ('gavebeløp', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10)),
                ('beløpsgrense', models.DecimalField(decimal_places=2, help_text='Amount limit', max_digits=10)),
                ('skattefradrag_fødselsnummer', models.CharField(help_text='National ID number for tax deduction', max_length=11)),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when form was submitted')),
                ('personel_number', models.CharField(help_text='Personnel number', max_length=50)),
                ('skip', models.BooleanField(default=False, help_text='Whether to skip this form')),
                ('signature', models.TextField(help_text='Base64 encoded signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Form',
                'verbose_name_plural': 'Campaign Forms',
                'db_table': 'campaign_form',
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaign_fo_campaig_e26307_idx'), models.Index(fields=['sales_rep_id'], name='campaign_fo_sales_r_21febf_idx'), models.Index(fields=['current_date'], name='campaign_fo_current_387da9_idx')],
            },
        ),
    ]
