# Generated by Django 4.2.7 on 2025-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaignform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignform',
            name='sales_rep_id',
            field=models.UUIDField(blank=True, help_text='ID of the manager or employee who submitted the form', null=True),
        ),
    ]
