# Generated by Django 4.2.7 on 2025-07-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_campaign'),
        ('campaigns', '0006_alter_campaignform_sales_rep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignform',
            name='address_text',
            field=models.CharField(blank=True, help_text='Street address', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Associated address - when address is deleted, this form is also deleted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_forms', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='posted',
            field=models.CharField(blank=True, help_text='City/Postal area', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='postnummer',
            field=models.CharField(blank=True, help_text='Postal code', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='campaignform',
            index=models.Index(fields=['address'], name='campaign_fo_address_3135b0_idx'),
        ),
    ]
