# Generated by Django 4.2.7 on 2025-07-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaignform_address_text_alter_campaignform_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignform',
            name='beløpsgrense',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount limit', max_digits=10, null=True),
        ),
    ]
