# Generated by Django 4.2.7 on 2025-07-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_campaign'),
        ('campaigns', '0008_alter_campaignform_beløpsgrense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignform',
            name='address',
            field=models.ForeignKey(blank=True, db_column='address_id', help_text='Associated address - when address is deleted, this form is also deleted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_forms', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='campaign',
            field=models.ForeignKey(db_column='campaign_id', help_text='Campaign this form belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='campaigns.campaign'),
        ),
    ]
