# Generated by Django 4.2.7 on 2025-07-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_campaignform_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignform',
            name='personel_number',
            field=models.CharField(blank=True, help_text='Personnel number', max_length=50, null=True),
        ),
    ]
