# Generated by Django 4.2.7 on 2025-07-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaignform_personel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignform',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name of the person', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='gavebeløp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Donation amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='kontonummer',
            field=models.CharField(blank=True, help_text='Account number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name of the person', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature', null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='skattefradrag_fødselsnummer',
            field=models.CharField(blank=True, help_text='National ID number for tax deduction', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='campaignform',
            name='sms_phone_number',
            field=models.CharField(blank=True, help_text='SMS phone number', max_length=20, null=True),
        ),
    ]
