# Generated by Django 4.2.7 on 2025-07-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_campaignform_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignform',
            name='external_agreement_id',
            field=models.CharField(blank=True, help_text='Agreement ID from LagreGiveravtale API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='external_person_id',
            field=models.CharField(blank=True, help_text='PersonId from LagrePerson API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='kid_error_message',
            field=models.TextField(blank=True, help_text='Error message if KID generation failed', null=True),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='kid_generated_at',
            field=models.DateTimeField(blank=True, help_text='When KID was generated', null=True),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='kid_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Status of KID generation', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignform',
            name='kid_number',
            field=models.CharField(blank=True, help_text='Generated KID number', max_length=50, null=True),
        ),
    ]
