# Generated by Django 4.2.7 on 2025-10-16 13:49

from django.db import migrations, connection


def safe_add_created_by_field(apps, schema_editor):
    """Safely add created_by field if it doesn't exist."""
    with connection.cursor() as cursor:
        # Check if created_by_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'campaign' 
            AND column_name = 'created_by_id'
        """)
        created_by_exists = cursor.fetchone() is not None
        
        # Add created_by_id if it doesn't exist
        if not created_by_exists:
            cursor.execute("""
                ALTER TABLE campaign 
                ADD COLUMN created_by_id UUID REFERENCES manager(id) ON DELETE CASCADE
            """)
            print("Added created_by_id column to campaign table")
        else:
            print("created_by_id column already exists in campaign table")


def reverse_add_created_by_field(apps, schema_editor):
    """Reverse operation - remove created_by field."""
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE campaign 
            DROP COLUMN IF EXISTS created_by_id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaignform_external_agreement_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            safe_add_created_by_field,
            reverse_add_created_by_field,
        ),
    ]
