# Generated by Django 4.2.7 on 2025-10-22 11:57

from django.db import migrations, connection


def check_and_add_campaign_area_foreign_keys(apps, schema_editor):
    """Check if foreign key columns exist and add them if they don't."""
    with connection.cursor() as cursor:
        # Check if campaign_area table exists at all
        cursor.execute("""
            SELECT 1 FROM information_schema.tables
            WHERE table_name = 'campaign_area'
        """)
        if cursor.fetchone() is None:
            # Table doesn't exist yet (e.g. fresh test DB). Nothing to fix.
            return

        # Check if campaign_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'campaign_area' 
            AND column_name = 'campaign_id'
        """)
        campaign_id_exists = cursor.fetchone() is not None
        
        # Check if area_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'campaign_area' 
            AND column_name = 'area_id'
        """)
        area_id_exists = cursor.fetchone() is not None
        
        # Add campaign_id if it doesn't exist
        if not campaign_id_exists:
            cursor.execute("""
                ALTER TABLE campaign_area 
                ADD COLUMN campaign_id UUID REFERENCES campaign(id) ON DELETE CASCADE
            """)
            print("Added campaign_id column to campaign_area table")
        
        # Add area_id if it doesn't exist
        if not area_id_exists:
            cursor.execute("""
                ALTER TABLE campaign_area 
                ADD COLUMN area_id UUID REFERENCES area(id) ON DELETE CASCADE
            """)
            print("Added area_id column to campaign_area table")
        
        # Add unique constraint if it doesn't exist
        cursor.execute("""
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'campaign_area' 
            AND constraint_type = 'UNIQUE'
            AND constraint_name LIKE '%campaign_area_campaign_id_area_id%'
        """)
        unique_constraint_exists = cursor.fetchone() is not None
        
        if not unique_constraint_exists:
            cursor.execute("""
                ALTER TABLE campaign_area 
                ADD CONSTRAINT campaign_area_campaign_id_area_id_unique 
                UNIQUE (campaign_id, area_id)
            """)
            print("Added unique constraint to campaign_area table")


def reverse_add_campaign_area_foreign_keys(apps, schema_editor):
    """Reverse operation - remove foreign key columns."""
    with connection.cursor() as cursor:
        # Remove unique constraint
        cursor.execute("""
            ALTER TABLE campaign_area 
            DROP CONSTRAINT IF EXISTS campaign_area_campaign_id_area_id_unique
        """)
        
        # Remove columns
        cursor.execute("""
            ALTER TABLE campaign_area 
            DROP COLUMN IF EXISTS campaign_id
        """)
        
        cursor.execute("""
            ALTER TABLE campaign_area 
            DROP COLUMN IF EXISTS area_id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20251016_1349'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_campaign_area_foreign_keys,
            reverse_add_campaign_area_foreign_keys,
        ),
    ]
