# Generated by Django 4.2.7 on 2025-11-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_ab_person_id'),
        ('campaigns', '0016_sync_campaign_area_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignemployee',
            options={'verbose_name': 'Campaign Assignment', 'verbose_name_plural': 'Campaign Assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='campaignemployee',
            unique_together={('campaign', 'employee')},
        ),
        migrations.AddField(
            model_name='campaignemployee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='users.manager'),
        ),
        migrations.AlterField(
            model_name='campaignemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='users.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignemployee',
            unique_together={('campaign', 'manager'), ('campaign', 'employee')},
        ),
        migrations.AddConstraint(
            model_name='campaignemployee',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('employee__isnull', False), ('manager__isnull', True)), models.Q(('employee__isnull', True), ('manager__isnull', False)), _connector='OR'), name='campaign_employee_exactly_one_person'),
        ),
    ]
