# Generated by Django 4.2.7 on 2026-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaign_brand_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand_color_hex',
            field=models.CharField(blank=True, help_text='Optional QC UI accent color (#RRGGBB); unset means default theme', max_length=7, null=True),
        ),
    ]
