# Generated by Django 4.2.7 on 2025-08-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # First, add the new managers field
        migrations.AddField(
            model_name='employee',
            name='managers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Managers who can manage this employee',
                related_name='managed_employees',
                to='users.manager'
            ),
        ),
        
        # Then remove the old manager field
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
