# Generated by Django 4.2.7 on 2026-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_ab_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('maps_emp', 'Maps Employee'), ('qc_emp', 'QC Employee')], help_text='Employee type - only for employees, not managers', max_length=20, null=True),
        ),
    ]
