# Generated by Django 4.2.7 on 2026-02-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('maps_admin', 'Maps Admin'), ('qc_admin', 'QC Admin')], help_text='Admin type - only for superusers (is_superuser=True and is_staff=True)', max_length=20, null=True),
        ),
    ]
