# Generated by Django 4.2.7 on 2026-04-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales_chief',
            field=models.BooleanField(db_index=True, default=False, help_text='Sales chief — included in QC sales-chief directory when True'),
        ),
    ]
