# Generated by Django 4.2.7 on 2026-04-20 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_sales_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChiefTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chief_memberships', to=settings.AUTH_USER_MODEL)),
                ('sales_chief', models.ForeignKey(limit_choices_to={'is_sales_chief': True}, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Chief Team Member',
                'verbose_name_plural': 'Sales Chief Team Members',
                'db_table': 'sales_chief_team_member',
                'unique_together': {('sales_chief', 'member')},
            },
        ),
    ]
