# Generated by Django 4.2.7 on 2025-07-15 00:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Unique identifier for the device sending location data', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(help_text='GPS coordinates (latitude, longitude) in WGS84 format', srid=4326)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters (optional)', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in meters per second (optional)', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees (0-360, optional)', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters (optional)', null=True)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery level percentage (optional)', null=True)),
                ('is_moving', models.BooleanField(default=False, help_text='Whether the device is currently moving')),
            ],
            options={
                'verbose_name': 'Location Ping',
                'verbose_name_plural': 'Location Pings',
                'db_table': 'location_ping',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change', models.JSONField(help_text='JSON data representing the offline change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tracking Sync Queue Item',
                'verbose_name_plural': 'Tracking Sync Queue Items',
                'db_table': 'tracking_sync_queue_item',
                'ordering': ['created_at'],
            },
        ),
    ]
