# Generated by Django 4.2.7 on 2025-07-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Associated employee (optional, can be null for anonymous tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='users.employee'),
        ),
        migrations.AddField(
            model_name='locationping',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Associated manager (optional, can be null for anonymous tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='users.manager'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['device_id', '-timestamp'], name='location_pi_device__82da73_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['employee', '-timestamp'], name='location_pi_employe_dd0ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['manager', '-timestamp'], name='location_pi_manager_f18732_idx'),
        ),
        migrations.AddIndex(
            model_name='locationping',
            index=models.Index(fields=['timestamp'], name='location_pi_timesta_124104_idx'),
        ),
    ]
