# Generated by Django 4.2.7 on 2026-04-21 10:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_sales_chief_team_member'),
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('websocket', 'WebSocket'), ('manual', 'Manual'), ('reaper_closed', 'Reaper Closed')], default='websocket', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='users.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='users.manager')),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'db_table': 'work_session',
                'indexes': [models.Index(fields=['employee', '-started_at'], name='work_sessio_employe_c90297_idx'), models.Index(fields=['manager', '-started_at'], name='work_sessio_manager_7f2d44_idx'), models.Index(condition=models.Q(('employee__isnull', False), ('ended_at__isnull', True)), fields=['employee'], name='ws_emp_open_idx'), models.Index(condition=models.Q(('ended_at__isnull', True), ('manager__isnull', False)), fields=['manager'], name='ws_mgr_open_idx'), models.Index(fields=['last_heartbeat_at'], name='work_sessio_last_he_3a3c54_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('employee__isnull', False), ('manager__isnull', True)), models.Q(('employee__isnull', True), ('manager__isnull', False)), _connector='OR'), name='work_session_exactly_one_actor'),
        ),
    ]
