# Generated by Django 4.2.7 on 2026-02-25 21:41
# Modified to check if columns exist before adding them

from django.db import migrations, models
import django.db.models.deletion


def add_created_by_if_not_exists(apps, schema_editor):
    """Add created_by_id column only if it doesn't exist."""
    db = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'area' 
            AND column_name = 'created_by_id'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE area 
                ADD COLUMN created_by_id UUID NULL 
                REFERENCES manager(id) ON DELETE SET NULL
            """)
            # Add index
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS area_created_by_id_idx 
                ON area(created_by_id)
            """)


def add_manager_if_not_exists(apps, schema_editor):
    """Add manager_id column only if it doesn't exist."""
    db = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'area' 
            AND column_name = 'manager_id'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE area 
                ADD COLUMN manager_id UUID NULL 
                REFERENCES manager(id) ON DELETE SET NULL
            """)
            # Add index
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS area_manager_id_idx 
                ON area(manager_id)
            """)


def reverse_add_created_by(apps, schema_editor):
    """Remove created_by_id column if it exists."""
    db = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'area' 
            AND column_name = 'created_by_id'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE area DROP COLUMN IF EXISTS created_by_id")


def reverse_add_manager(apps, schema_editor):
    """Remove manager_id column if it exists."""
    db = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'area' 
            AND column_name = 'manager_id'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE area DROP COLUMN IF EXISTS manager_id")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_employee_type'),
        ('areas', '0009_area_created_by_area_employees_area_manager_and_more'),
    ]

    operations = [
        # Add created_by field conditionally (only if column doesn't exist)
        migrations.RunPython(add_created_by_if_not_exists, reverse_add_created_by),
        # Add manager field conditionally (only if column doesn't exist)
        migrations.RunPython(add_manager_if_not_exists, reverse_add_manager),
    ]
