# Generated by Django 4.2.7 on 2026-04-08 18:19
#
# IMPORTANT: areas.0009 and areas.0010 already add `created_by_id` and `manager_id`
# to table `area` via RunPython + raw SQL (idempotent). A later makemigrations run
# produced AddField operations that would duplicate those columns and fail with
# DuplicateColumn. This migration only updates Django's *migration state* to match
# the database; it does not ALTER the area table.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_sales_chief'),
        ('areas', '0010_area_created_by_area_manager'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Columns already exist from 0009/0010 — do not run AddField SQL again.
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='area',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text='Manager who created this area',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_areas',
                        to='users.manager',
                    ),
                ),
                migrations.AddField(
                    model_name='area',
                    name='manager',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='managed_areas',
                        to='users.manager',
                    ),
                ),
            ],
        ),
    ]
