# Generated by Django 4.2.7 on 2026-02-27 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_user_admin_type'),
        ('campaigns', '0017_add_manager_to_campaign_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAssignment',
            fields=[
                ('qc_employee', models.OneToOneField(help_text='QC employee these stats belong to', limit_choices_to={'employee_type': 'qc_emp'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='qc_assignment_stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_assigned', models.IntegerField(default=0, help_text='Total contacts ever assigned to this employee')),
                ('active_assigned', models.IntegerField(default=0, help_text='Contacts currently assigned and not yet completed')),
                ('completed_today', models.IntegerField(default=0, help_text='Contacts completed today (resets daily)')),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_reset_at', models.DateField(auto_now_add=True, help_text='Date of last reset (for daily reset of completed_today)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QC Contact Assignment',
                'verbose_name_plural': 'QC Contact Assignments',
                'db_table': 'qc_contact_assignment',
            },
        ),
        migrations.CreateModel(
            name='QCContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(help_text="Format: '+47 XXX XX XXX'", max_length=50)),
                ('seller_name', models.CharField(help_text='Original seller who created this contact', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('qc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('til_behandling', 'To be processed'), ('forste_oppring', 'First call attempt'), ('andre_oppring', 'Second call attempt'), ('tredje_oppring', 'Third call attempt'), ('si_opp', 'Cancellation requested'), ('negativ_tilbakemelding', 'Negative feedback'), ('positiv_tilbakemelding', 'Positive feedback'), ('other_inquiries', 'Other inquiries')], default='til_behandling', help_text='Current workflow status', max_length=50)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of call attempts (0-3)')),
                ('urgent', models.BooleanField(default=False)),
                ('urgent_message', models.TextField(blank=True)),
                ('qc_result', models.CharField(blank=True, choices=[('Svarte', 'Answered'), ('Ikke svar', 'No answer'), ('Opptatt', 'Busy')], help_text='Result of the QC call', max_length=20, null=True)),
                ('svarte_category', models.CharField(blank=True, choices=[('negativ', 'Negative'), ('positiv', 'Positive'), ('annen', 'Other')], help_text="Sub-category when qc_result is 'Svarte'", max_length=20, null=True)),
                ('si_opp', models.CharField(blank=True, choices=[('JA', 'Yes'), ('NEI', 'No')], help_text='Whether customer wants to cancel (JA/NEI)', max_length=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('qc_agent_name', models.CharField(blank=True, help_text='Name of the QC agent who processed this contact', max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='QC employee assigned to process this contact', limit_choices_to={'employee_type': 'qc_emp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_qc_contacts', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this contact belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_contacts', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'QC Contact',
                'verbose_name_plural': 'QC Contacts',
                'db_table': 'qc_contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCSettings',
            fields=[
                ('user', models.OneToOneField(help_text='User these settings belong to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='qc_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('daily_goal', models.IntegerField(default=100, help_text='Target number of calls per day')),
                ('auto_copy_phone', models.BooleanField(default=True, help_text='Auto-copy phone number to clipboard')),
                ('theme', models.CharField(choices=[('lys', 'Light'), ('mork', 'Dark'), ('system', 'System')], default='lys', help_text='UI theme preference', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QC Settings',
                'verbose_name_plural': 'QC Settings',
                'db_table': 'qc_settings',
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0, help_text='Number of contacts imported')),
                ('status', models.CharField(choices=[('Fullfort', 'Completed'), ('Feilet', 'Failed'), ('Behandler', 'Processing')], default='Behandler', help_text='Import status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, help_text='Date of import (YYYY-MM-DD)')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this import belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_imports', to='campaigns.campaign')),
                ('imported_by', models.ForeignKey(blank=True, help_text='User who performed this import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QC Import Record',
                'verbose_name_plural': 'QC Import Records',
                'db_table': 'qc_import_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('qc_result', models.CharField(choices=[('Svarte', 'Answered'), ('Ikke svar', 'No answer'), ('Opptatt', 'Busy')], help_text='Result of the QC call', max_length=20)),
                ('svarte_category', models.CharField(blank=True, choices=[('negativ', 'Negative'), ('positiv', 'Positive'), ('annen', 'Other')], help_text="Sub-category when qc_result is 'Svarte'", max_length=20, null=True)),
                ('si_opp', models.CharField(blank=True, choices=[('JA', 'Yes'), ('NEI', 'No')], help_text='Whether customer wants to cancel (JA/NEI)', max_length=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('qc_agent_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, help_text='Date for efficient date filtering (YYYY-MM-DD)')),
                ('tid', models.CharField(help_text="Time in 'HH:MM' format (24-hour)", max_length=5)),
                ('contact', models.ForeignKey(help_text='Original contact this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='qc_system.qccontact')),
                ('qc_agent', models.ForeignKey(blank=True, help_text='QC agent who processed this call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QC History',
                'verbose_name_plural': 'QC History Entries',
                'db_table': 'qc_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact'], name='qc_history_contact_d9f742_idx'), models.Index(fields=['qc_agent'], name='qc_history_qc_agen_a035be_idx'), models.Index(fields=['date'], name='qc_history_date_8e7ad4_idx'), models.Index(fields=['created_at'], name='qc_history_created_357d5f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['status'], name='qc_contact_status_4334c2_idx'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['assigned_to'], name='qc_contact_assigne_720c00_idx'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['seller_name'], name='qc_contact_seller__cdd0da_idx'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['created_at'], name='qc_contact_created_6f0720_idx'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['urgent'], name='qc_contact_urgent_65247e_idx'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['campaign'], name='qc_contact_campaig_fea608_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['date'], name='qc_import_r_date_d959a4_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['status'], name='qc_import_r_status_9ec2ab_idx'),
        ),
    ]
