# Generated by Django 4.2.7 on 2026-02-27 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qccontact',
            name='attempt_count',
            field=models.IntegerField(default=0, help_text='Number of call attempts (0-3 typical, max 10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='qccontact',
            name='status',
            field=models.CharField(choices=[('til_behandling', 'To be processed'), ('forste_oppring', 'First call attempt'), ('andre_oppring', 'Second call attempt'), ('tredje_oppring', 'Third call attempt'), ('si_opp', 'Cancellation requested'), ('negativ_tilbakemelding', 'Negative feedback'), ('positiv_tilbakemelding', 'Positive feedback'), ('other_inquiries', 'Other inquiries')], db_index=True, default='til_behandling', help_text='Current workflow status', max_length=50),
        ),
        migrations.AlterField(
            model_name='qcsettings',
            name='daily_goal',
            field=models.IntegerField(default=100, help_text='Target number of calls per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['campaign', 'date'], name='qc_import_campaign_date'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['assigned_to', 'status'], name='qc_contact_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['assigned_to', 'status', 'urgent'], name='qc_contact_assignee_status_urg'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['assigned_to', 'status', 'created_at'], name='qc_contact_assignee_status_cr'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['campaign', 'status'], name='qc_contact_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='qchistory',
            index=models.Index(fields=['qc_agent', 'date'], name='qc_history_agent_date'),
        ),
        migrations.AddIndex(
            model_name='qchistory',
            index=models.Index(fields=['date', 'qc_result'], name='qc_history_date_result'),
        ),
        migrations.AddIndex(
            model_name='qchistory',
            index=models.Index(fields=['qc_agent', 'date', 'qc_result'], name='qc_history_agent_date_result'),
        ),
        migrations.AddConstraint(
            model_name='qccontact',
            constraint=models.CheckConstraint(check=models.Q(('attempt_count__gte', 0), ('attempt_count__lte', 10)), name='qc_contact_attempt_count_range'),
        ),
    ]
