# Generated by Django 4.2.7 on 2026-03-24 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc_system', '0008_user_added_import_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCTransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('requested_count', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QC Transfer Request',
                'verbose_name_plural': 'QC Transfer Requests',
                'db_table': 'qc_transfer_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCTransferRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QC Transfer Request Item',
                'verbose_name_plural': 'QC Transfer Request Items',
                'db_table': 'qc_transfer_request_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='qccheckoff',
            new_name='qc_check_of_user_id_47464a_idx',
            old_name='qc_check_off_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='qccheckoff',
            new_name='qc_check_of_contact_f0fad1_idx',
            old_name='qc_check_off_contact_id_idx',
        ),
        migrations.RenameIndex(
            model_name='qcfavourite',
            new_name='qc_favourit_user_id_857024_idx',
            old_name='qc_favourite_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='qcfavourite',
            new_name='qc_favourit_contact_a40c5d_idx',
            old_name='qc_favourite_contact_id_idx',
        ),
        migrations.AddField(
            model_name='qctransferrequestitem',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_request_items', to='qc_system.qccontact'),
        ),
        migrations.AddField(
            model_name='qctransferrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qc_system.qctransferrequest'),
        ),
        migrations.AddField(
            model_name='qctransferrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_transfer_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qctransferrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_transfer_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qctransferrequest',
            name='target_agent',
            field=models.ForeignKey(help_text='Intended recipient of transferred contacts', on_delete=django.db.models.deletion.PROTECT, related_name='qc_transfer_requests_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='qctransferrequestitem',
            index=models.Index(fields=['request'], name='qc_transfer_request_99508c_idx'),
        ),
        migrations.AddIndex(
            model_name='qctransferrequestitem',
            index=models.Index(fields=['contact'], name='qc_transfer_contact_794139_idx'),
        ),
        migrations.AddConstraint(
            model_name='qctransferrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'contact'), name='qc_transfer_request_item_request_contact_unique'),
        ),
        migrations.AddIndex(
            model_name='qctransferrequest',
            index=models.Index(fields=['status', 'created_at'], name='qc_tr_req_status_created'),
        ),
        migrations.AddIndex(
            model_name='qctransferrequest',
            index=models.Index(fields=['requested_by', 'status'], name='qc_tr_req_requester_status'),
        ),
        migrations.AddIndex(
            model_name='qctransferrequest',
            index=models.Index(fields=['target_agent', 'status'], name='qc_tr_req_target_status'),
        ),
    ]
