# Generated by Django 4.2.7 on 2026-03-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0011_gamification_models_and_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecord',
            name='list_name',
            field=models.CharField(blank=True, db_index=True, help_text='Human-friendly list name set at import time', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importrecord',
            name='list_slug',
            field=models.SlugField(blank=True, help_text='Normalized list identifier for API filtering and uniqueness', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qccontact',
            name='import_record',
            field=models.ForeignKey(blank=True, help_text='Import record/list this contact originated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='qc_system.importrecord'),
        ),
        migrations.AddField(
            model_name='qcsettings',
            name='selected_import_record',
            field=models.ForeignKey(blank=True, help_text='Selected import list context for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='qc_system.importrecord'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['list_slug'], name='qc_import_r_list_sl_5aee73_idx'),
        ),
        migrations.AddIndex(
            model_name='importrecord',
            index=models.Index(fields=['campaign', 'list_slug'], name='qc_import_campaign_list_slug'),
        ),
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['import_record', 'assigned_to', 'status', 'urgent', 'created_at'], name='qc_contact_imp_asg_st_urg_cr'),
        ),
        migrations.AddConstraint(
            model_name='importrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('list_slug__isnull', False)), fields=('campaign', 'list_slug'), name='qc_import_campaign_list_slug_unique'),
        ),
    ]
