# Generated by Django 4.2.7 on 2026-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0013_saleschief_notify_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleschiefnotifylog',
            name='contacts_snapshot',
            field=models.JSONField(default=list, help_text='Snapshot list of contact dicts at send time (id, name, seller, sale_date, status_label, comment)'),
        ),
    ]
