# Generated by Django 4.2.7 on 2026-04-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0015_qccheckoff_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qccheckoff',
            new_name='qc_check_of_user_id_bf284c_idx',
            old_name='qc_check_off_user_scope_idx',
        ),
    ]
