# Generated by Django 4.2.7 on 2026-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0018_audit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccontact',
            name='sales_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
