# Generated by Django 4.2.7 on 2026-04-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0019_add_sales_id_to_qccontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='qccontact',
            name='contact_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
