# Generated by Django 4.2.7 on 2026-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_system', '0020_qccontact_contact_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qccontact',
            index=models.Index(fields=['campaign', 'user_added_import_date', 'created_at'], name='qc_contact_campaign_date_cr'),
        ),
    ]
