# Generated by Django 4.2.7 on 2026-02-25 21:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMapSearch',
            fields=[
                ('address_uuid', models.CharField(help_text='Address UUID or generated coordinate key', max_length=255, primary_key=True, serialize=False)),
                ('full_address', models.TextField(help_text='Full address string')),
                ('postcode', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True)),
                ('city', models.TextField(blank=True, help_text='City/post area name', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Centroid point of the building', srid=4326)),
                ('units', models.JSONField(blank=True, default=list, help_text='Array of unit objects (only for apartment buildings)', null=True)),
                ('unit_count', models.IntegerField(default=0, help_text='Number of units. 0 = house, >0 = apartment building')),
            ],
            options={
                'db_table': 'cache_map_search',
                'managed': False,
            },
        ),
    ]
