# Generated by Django 4.2.7 on 2025-08-31 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LESSON_STARTED', 'Lesson Started'), ('LESSON_COMPLETED', 'Lesson Completed'), ('LESSON_PAUSED', 'Lesson Paused'), ('LESSON_RESUMED', 'Lesson Resumed'), ('QUIZ_SUBMITTED', 'Quiz Submitted'), ('QUIZ_FAILED', 'Quiz Failed'), ('SECTION_STARTED', 'Section Started'), ('SECTION_COMPLETED', 'Section Completed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Learning Activity Log',
                'verbose_name_plural': 'Learning Activity Logs',
                'db_table': 'learning_activity_log',
            },
        ),
        migrations.CreateModel(
            name='LearningPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Learning Prerequisite',
                'verbose_name_plural': 'Learning Prerequisites',
                'db_table': 'learning_prerequisite',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Text'), ('QUIZ', 'Quiz')], default='TEXT', max_length=10)),
                ('content_url', models.TextField(blank=True, help_text='URL or reference (can be empty for quiz)')),
                ('order', models.PositiveIntegerField(blank=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_estimate_minutes', models.PositiveIntegerField(default=0)),
                ('pass_threshold_percent', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Learning Lesson',
                'verbose_name_plural': 'Learning Lessons',
                'db_table': 'learning_lesson',
                'ordering': ['section__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'db_table': 'learning_quiz_answer',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'learning_quiz_attempt',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'learning_quiz_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(blank=True, db_index=True, help_text='Display order (1,2,3..)')),
                ('is_active', models.BooleanField(default=True)),
                ('duration_estimate_minutes', models.PositiveIntegerField(default=0)),
                ('icon_emoji', models.CharField(blank=True, default='📚', max_length=10)),
                ('icon_color', models.CharField(blank=True, default='bg-green-500', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Section',
                'verbose_name_plural': 'Learning Sections',
                'db_table': 'learning_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_section_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Section Progress',
                'verbose_name_plural': 'User Section Progress',
                'db_table': 'learning_user_section_progress',
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Lesson Progress',
                'verbose_name_plural': 'User Lesson Progress',
                'db_table': 'learning_user_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='UserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_streak_days', models.PositiveIntegerField(default=0)),
                ('total_learning_time_minutes', models.PositiveIntegerField(default=0)),
                ('last_learning_date', models.DateField(null=True)),
                ('current_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.lesson')),
                ('current_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learning Path',
                'verbose_name_plural': 'User Learning Paths',
                'db_table': 'learning_user_learning_path',
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active', 'order'], name='learning_se_is_acti_f7e29e_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['slug'], name='learning_se_slug_b5d30c_idx'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizquestion'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.section'),
        ),
        migrations.AddField(
            model_name='learningprerequisite',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='learningprerequisite',
            name='prerequisite_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks_lessons', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='learningprerequisite',
            name='prerequisite_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks_sections', to='learning.section'),
        ),
        migrations.AddField(
            model_name='learningprerequisite',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.section'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.section'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersectionprogress',
            index=models.Index(fields=['user', 'section'], name='learning_us_user_id_1b2870_idx'),
        ),
        migrations.AddIndex(
            model_name='usersectionprogress',
            index=models.Index(fields=['section', 'status'], name='learning_us_section_3c207d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersectionprogress',
            index=models.Index(fields=['last_activity_at'], name='learning_us_last_ac_c26bcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersectionprogress',
            unique_together={('user', 'section')},
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='learning_us_user_id_42ca39_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['lesson', 'status'], name='learning_us_lesson__7960ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['last_activity_at'], name='learning_us_last_ac_ceec6d_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'status'], name='learning_us_user_id_796599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('lesson', 'order')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['lesson', 'user', 'submitted_at'], name='learning_qu_lesson__a9d994_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'passed'], name='learning_qu_user_id_a956fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('question', 'order')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['section', 'is_active', 'order'], name='learning_le_section_f852ce_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['kind', 'is_active'], name='learning_le_kind_6a56c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('section', 'order'), ('section', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='learningprerequisite',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lesson__isnull', True), ('section__isnull', False)), models.Q(('lesson__isnull', False), ('section__isnull', True)), _connector='OR'), name='prerequisite_target_constraint'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='learning_ac_created_9b13dc_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'event'], name='learning_ac_user_id_9665e7_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['section', 'event'], name='learning_ac_section_c587b7_idx'),
        ),
    ]
