# Generated by Django 4.2.7 on 2026-02-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_add_learning_media_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='learning_se_is_acti_f7e29e_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='learning_se_slug_b5d30c_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmedia',
            new_name='learning_me_content_cb40bb_idx',
            old_name='learning_me_content_ce9c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmedia',
            new_name='learning_me_uploade_5278a1_idx',
            old_name='learning_me_uploade_af4f52_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmedia',
            new_name='learning_me_media_t_4def77_idx',
            old_name='learning_me_media_t_b7d8a1_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmedia',
            new_name='learning_me_storage_8e1361_idx',
            old_name='learning_me_storage_type_idx',
        ),
        migrations.RenameIndex(
            model_name='learningmedia',
            new_name='learning_me_externa_9c1ecf_idx',
            old_name='learning_me_ext_file_id_idx',
        ),
        migrations.RenameIndex(
            model_name='section',
            new_name='learning_se_campaig_c537f1_idx',
            old_name='learning_sec_campaign_active_order',
        ),
        migrations.RenameIndex(
            model_name='section',
            new_name='learning_se_campaig_a33626_idx',
            old_name='learning_sec_campaign_slug',
        ),
        migrations.RenameIndex(
            model_name='section',
            new_name='learning_se_is_acti_1f41f4_idx',
            old_name='learning_sec_active',
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Display order (1,2,3..)'),
        ),
        migrations.AlterField(
            model_name='userlearningpath',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL),
        ),
    ]
