# Generated by Django 4.2.7 on 2025-08-03 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0012_campaignform_external_agreement_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_text', models.CharField(help_text='Full address from CSV', max_length=255)),
                ('latitude', models.FloatField(blank=True, default=None, help_text='Geocoded latitude', null=True)),
                ('longitude', models.FloatField(blank=True, default=None, help_text='Geocoded longitude', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When the address was uploaded')),
                ('geocoded_at', models.DateTimeField(blank=True, help_text='When the address was successfully geocoded', null=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_addresses', to='campaigns.campaign')),
                ('manager', models.ForeignKey(help_text='Manager who uploaded this address', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_addresses', to='users.manager')),
            ],
            options={
                'verbose_name': 'Uploaded Address',
                'verbose_name_plural': 'Uploaded Addresses',
                'db_table': 'uploaded_address',
                'indexes': [models.Index(fields=['campaign', 'manager'], name='uploaded_ad_campaig_a1057f_idx'), models.Index(fields=['latitude', 'longitude'], name='uploaded_ad_latitud_ce29fd_idx'), models.Index(fields=['geocoded_at'], name='uploaded_ad_geocode_b3e686_idx')],
            },
        ),
    ]
