# Generated by Django 4.2.7 on 2025-08-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedaddress',
            name='batch_sequence',
            field=models.IntegerField(blank=True, help_text='Order within the batch (1, 2, 3...)', null=True),
        ),
        migrations.AddField(
            model_name='uploadedaddress',
            name='batch_total',
            field=models.IntegerField(blank=True, help_text='Total addresses in this batch', null=True),
        ),
        migrations.AddField(
            model_name='uploadedaddress',
            name='upload_batch_id',
            field=models.UUIDField(blank=True, help_text='Groups addresses from same upload batch', null=True),
        ),
        migrations.AddIndex(
            model_name='uploadedaddress',
            index=models.Index(fields=['upload_batch_id', 'batch_sequence'], name='upload_batch_idx'),
        ),
    ]
