# Generated by Django 4.2.7 on 2025-11-13 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_addresses', '0002_uploadedaddress_batch_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedaddress',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geocoded point geometry (from longitude/latitude)', null=True, srid=4326),
        ),
    ]
