# Generated by Django 4.2.7 on 2025-12-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_add_manager_to_campaign_employee'),
        ('users', '0004_add_ab_person_id'),
        ('uploaded_addresses', '0003_uploadedaddress_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStatus',
            fields=[
                ('batch_id', models.UUIDField(help_text='Unique batch identifier', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', help_text='Current status of the batch', max_length=20)),
                ('total_addresses', models.IntegerField(default=0, help_text='Total number of addresses in this batch')),
                ('processed_addresses', models.IntegerField(default=0, help_text='Number of addresses processed so far')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the batch was created')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the batch was cancelled', null=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batch_statuses', to='campaigns.campaign')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Manager who cancelled this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_batches', to='users.manager')),
                ('manager', models.ForeignKey(help_text='Manager who created this batch', on_delete=django.db.models.deletion.CASCADE, related_name='batch_statuses', to='users.manager')),
            ],
            options={
                'verbose_name': 'Batch Status',
                'verbose_name_plural': 'Batch Statuses',
                'db_table': 'batch_status',
                'indexes': [models.Index(fields=['batch_id', 'status'], name='batch_statu_batch_i_0522a7_idx'), models.Index(fields=['manager', 'status'], name='batch_statu_manager_9e3467_idx'), models.Index(fields=['campaign', 'status'], name='batch_statu_campaig_021889_idx')],
            },
        ),
    ]
