# Generated by Django 4.2.7 on 2026-01-15 14:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0009_area_created_by_area_employees_area_manager_and_more'),
        ('campaigns', '0017_add_manager_to_campaign_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCarrierCache',
            fields=[
                ('phone_e164', models.CharField(help_text='Normalized E.164 format', max_length=20, primary_key=True, serialize=False)),
                ('carrier', models.CharField(help_text="Carrier name (e.g., 'Talkmore', 'Telenor')", max_length=100)),
                ('source', models.CharField(default='data247', help_text='Source of carrier data', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional TTL for cache invalidation', null=True)),
            ],
            options={
                'verbose_name': 'Phone Carrier Cache',
                'verbose_name_plural': 'Phone Carrier Caches',
                'db_table': 'talkmore_phone_carrier_cache',
            },
        ),
        migrations.CreateModel(
            name='EnrichmentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('discovering', 'Discovering'), ('enriching_1881', 'Enriching 1881'), ('enriching_carrier', 'Enriching Carrier'), ('writing', 'Writing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', help_text='Current status of the enrichment job', max_length=20)),
                ('expected_count', models.IntegerField(default=0, help_text='Total addresses inside polygon')),
                ('done_count', models.IntegerField(default=0, help_text='Addresses processed (including failed/no_data)')),
                ('success_count', models.IntegerField(default=0, help_text='Addresses with people+phones AND carrier matches')),
                ('no_data_count', models.IntegerField(default=0, help_text='Addresses with no 1881 data')),
                ('failed_count', models.IntegerField(default=0, help_text='Addresses that failed enrichment')),
                ('started_at', models.DateTimeField(blank=True, help_text='When discovery started', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When job completed', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(help_text='Area associated with this enrichment job', on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_jobs', to='areas.area', unique=True)),
                ('campaign', models.ForeignKey(help_text='Campaign associated with this job', on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_jobs', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Enrichment Job',
                'verbose_name_plural': 'Enrichment Jobs',
                'db_table': 'talkmore_enrichment_job',
            },
        ),
        migrations.CreateModel(
            name='EnrichedAddressResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address_uuid', models.UUIDField(help_text='Stable feature ID from local_apartments.address_uuid')),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Copy from local_apartments.position', srid=4326)),
                ('address_text', models.TextField(help_text='Full address string')),
                ('municipality_code', models.CharField(blank=True, help_text='Municipality code', max_length=20, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True)),
                ('people', models.JSONField(default=list, help_text='List of {name, phone_e164, carrier} objects')),
                ('carrier_summary', models.JSONField(default=dict, help_text="Object like {'Talkmore': 1, 'Telenor': 2}")),
                ('show_marker', models.BooleanField(default=False, help_text='True if any Talkmore/Telenor carrier')),
                ('status', models.CharField(choices=[('done', 'Done'), ('no_data', 'No Data'), ('failed', 'Failed')], default='done', help_text='Status of this address enrichment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(db_column='job_id', help_text='Enrichment job this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='address_results', to='talkmore_enrichment.enrichmentjob')),
            ],
            options={
                'verbose_name': 'Enriched Address Result',
                'verbose_name_plural': 'Enriched Address Results',
                'db_table': 'talkmore_enriched_address_result',
            },
        ),
        migrations.AddIndex(
            model_name='enrichmentjob',
            index=models.Index(fields=['status'], name='enrichment_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichedaddressresult',
            index=models.Index(fields=['job', 'show_marker'], name='enriched_result_job_marker_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichedaddressresult',
            index=models.Index(fields=['job', 'address_uuid'], name='enriched_result_job_uuid_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrichedaddressresult',
            constraint=models.UniqueConstraint(fields=('job', 'address_uuid'), name='unique_job_address'),
        ),
    ]
