# Generated by Django 4.2.7 on 2026-01-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0009_area_created_by_area_employees_area_manager_and_more'),
        ('talkmore_enrichment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichmentjob',
            name='area',
            field=models.OneToOneField(help_text='Area associated with this enrichment job (1 area = 1 job)', on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_job', to='areas.area'),
        ),
    ]
