# Generated by Django 4.2.7 on 2026-01-03 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0017_add_manager_to_campaign_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_key', models.CharField(help_text="e.g., 'fylke:03', 'kommune:0301', 'grunnkrets:03010101'", max_length=50)),
                ('area_type', models.CharField(choices=[('fylke', 'Fylke (County)'), ('kommune', 'Kommune (Municipality)'), ('grunnkrets', 'Grunnkrets (Basic District)')], help_text='Administrative level', max_length=20)),
                ('area_code', models.CharField(help_text='Administrative code (2, 4, or 8 digits)', max_length=10)),
                ('area_name', models.CharField(help_text='Administrative area name', max_length=255)),
                ('county_code', models.CharField(blank=True, help_text='County code for hierarchical queries', max_length=2, null=True)),
                ('municipality_code', models.CharField(blank=True, help_text='Municipality code for hierarchical queries', max_length=4, null=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag - false means unlocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mean_age', models.DecimalField(blank=True, decimal_places=1, help_text='Average age for the area from SSB (only for fylke/kommune)', max_digits=5, null=True)),
                ('median_age', models.DecimalField(blank=True, decimal_places=1, help_text='Median age for the area from SSB (only for fylke/kommune)', max_digits=5, null=True)),
                ('stats_year', models.IntegerField(blank=True, help_text='Year the statistics are from (e.g., 2025)', null=True)),
                ('stats_updated_at', models.DateTimeField(blank=True, help_text='When the stats were last fetched/updated from SSB', null=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='locked_areas', to='campaigns.campaign')),
                ('locked_by', models.ForeignKey(db_column='locked_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Locked Area',
                'verbose_name_plural': 'Locked Areas',
                'db_table': 'locked_areas',
                'indexes': [models.Index(fields=['campaign', 'area_type'], name='locked_area_campaig_12dfa0_idx'), models.Index(fields=['county_code'], name='locked_area_county__3a9fc7_idx'), models.Index(fields=['municipality_code'], name='locked_area_municip_909aa9_idx'), models.Index(fields=['is_active'], name='locked_area_is_acti_25ee48_idx'), models.Index(fields=['area_key'], name='locked_area_area_ke_b89831_idx')],
                'unique_together': {('campaign', 'area_key')},
            },
        ),
    ]
