# Generated by Django 4.2.7 on 2025-07-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee who created the address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.employee'),
        ),
        migrations.AddField(
            model_name='address',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager who created the address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.manager'),
        ),
    ]
