# Generated by Django 4.2.7 on 2025-07-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignemployee'),
        ('addresses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this address belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='campaigns.campaign'),
        ),
    ]
