# Generated by Django 4.2.7 on 2025-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_add_notes_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.CharField(choices=[('ja', 'Ja'), ('ikke_hjemme', 'Ikke hjemme'), ('nei', 'Nei'), ('folg_opp', 'Følg opp')], default='ja', max_length=20),
        ),
    ]
