# Generated by Django 4.2.7 on 2025-11-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial_building_model'),
        ('addresses', '0007_alter_address_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.ForeignKey(blank=True, help_text='If set, this address is part of a building (not a standalone house)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='buildings.building'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['building'], name='idx_addr_building'),
        ),
    ]
