# Generated by Django 4.2.7 on 2026-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_address_nei_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='nei_subcategory',
            field=models.CharField(blank=True, choices=[('ikke_interessert', 'Ikke interessert'), ('darlig_erfaring', 'Dårlig erfaring'), ('bindingstid', 'Bindingstid'), ('bedrift', 'Bedrift'), ('pris', 'Pris'), ('eksisterende_kunde', 'Eksisterende kunde')], help_text='When status is nei: reason for decline (optional)', max_length=40, null=True),
        ),
    ]
