# Generated by Django 4.2.7 on 2025-07-17 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('break', 'Break'), ('call', 'On Call'), ('after_work', 'After Work'), ('offline', 'Offline')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking', to='users.employee')),
            ],
            options={
                'verbose_name_plural': 'Time Tracking',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['employee', 'start_time'], name='dashboard_t_employe_b0108b_idx'), models.Index(fields=['status', 'start_time'], name='dashboard_t_status_894bce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('callback', 'Callback Requested'), ('no_answer', 'No Answer')], default='pending', max_length=20)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='areas.area')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='campaigns.campaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.manager')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='dashboard_s_status_4e4760_idx'), models.Index(fields=['employee', 'created_at'], name='dashboard_s_employe_57b3f5_idx'), models.Index(fields=['campaign', 'created_at'], name='dashboard_s_campaig_d96cb5_idx'), models.Index(fields=['outcome', 'created_at'], name='dashboard_s_outcome_79b11d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('period_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_call_duration', models.IntegerField(default=0)),
                ('total_work_time', models.IntegerField(default=0)),
                ('callback_requests', models.IntegerField(default=0)),
                ('no_answers', models.IntegerField(default=0)),
                ('not_home', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='areas.area')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='campaigns.campaign')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='users.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='users.manager')),
            ],
            options={
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['date', 'period_type'], name='dashboard_p_date_d3472e_idx'), models.Index(fields=['employee', 'date'], name='dashboard_p_employe_f68915_idx'), models.Index(fields=['campaign', 'date'], name='dashboard_p_campaig_5c59f9_idx'), models.Index(fields=['area', 'date'], name='dashboard_p_area_id_ca2f3f_idx')],
                'unique_together': {('date', 'hour', 'period_type', 'employee', 'manager', 'campaign', 'area')},
            },
        ),
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('online_employees', models.IntegerField(default=0)),
                ('total_employees', models.IntegerField(default=0)),
                ('active_employees', models.IntegerField(default=0)),
                ('total_work_time', models.IntegerField(default=0)),
                ('total_break_time', models.IntegerField(default=0)),
                ('total_call_time', models.IntegerField(default=0)),
                ('active_campaigns', models.IntegerField(default=0)),
                ('campaign_progress', models.JSONField(blank=True, default=dict)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_summaries', to='users.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_summaries', to='users.manager')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='dashboard_d_date_2cebd3_idx'), models.Index(fields=['manager', 'date'], name='dashboard_d_manager_8f9c90_idx'), models.Index(fields=['employee', 'date'], name='dashboard_d_employe_82df80_idx')],
                'unique_together': {('date', 'manager', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('address_contact', 'Address Contact'), ('location_update', 'Location Update'), ('area_assignment', 'Area Assignment'), ('status_change', 'Status Change'), ('login', 'User Login'), ('logout', 'User Logout'), ('campaign_start', 'Campaign Start'), ('campaign_end', 'Campaign End')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='areas.area')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.campaign')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.manager')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', 'created_at'], name='dashboard_a_activit_cda378_idx'), models.Index(fields=['employee', 'created_at'], name='dashboard_a_employe_884e13_idx'), models.Index(fields=['manager', 'created_at'], name='dashboard_a_manager_91f195_idx'), models.Index(fields=['campaign', 'created_at'], name='dashboard_a_campaig_deea3d_idx')],
            },
        ),
    ]
