# Generated by Django 4.2.7 on 2025-07-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('address_contact', 'Address Contact'), ('location_update', 'Location Update'), ('area_assignment', 'Area Assignment'), ('status_change', 'Status Change'), ('login', 'User Login'), ('logout', 'User Logout'), ('campaign_start', 'Campaign Start'), ('campaign_end', 'Campaign End'), ('vipps_contact', 'VIPPS Contact'), ('avtalegiro_contact', 'Avtalegiro Contact')], max_length=50),
        ),
    ]
