# Generated by Django 4.2.7 on 2026-02-11 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_add_manager_to_campaign_employee'),
        ('users', '0004_add_ab_person_id'),
        ('dashboard', '0002_alter_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global - All Users'), ('manager', 'Manager-Specific'), ('campaign', 'Campaign-Specific'), ('employee', 'Employee-Specific')], default='global', help_text='Who this threshold applies to', max_length=20)),
                ('min_doors_per_day', models.IntegerField(default=70, help_text='Minimum doors an employee should knock per day')),
                ('min_doors_per_week', models.IntegerField(default=350, help_text='Minimum doors per week (e.g. 70 * 5 working days)')),
                ('min_yes_rate_percent', models.DecimalField(decimal_places=2, default=30.0, help_text='Minimum acceptable yes-rate percentage (e.g. 30.00 = 30%)', max_digits=5)),
                ('max_no_rate_percent', models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum acceptable rejection rate (e.g. 50.00 = 50%)', max_digits=5)),
                ('min_contact_rate_percent', models.DecimalField(decimal_places=2, default=60.0, help_text='Minimum contact rate — doors where someone answered', max_digits=5)),
                ('consecutive_days_threshold', models.IntegerField(default=3, help_text='Consecutive poor days before a CRITICAL alert fires')),
                ('performance_drop_alert_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='Alert if performance drops by this % vs rolling average', max_digits=5)),
                ('max_inactive_hours', models.IntegerField(default=4, help_text='Alert if no door activity for this many hours during a work day')),
                ('is_active', models.BooleanField(default=True, help_text='Only active thresholds are evaluated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text="Required when scope is 'campaign'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_thresholds', to='campaigns.campaign')),
                ('employee', models.ForeignKey(blank=True, help_text="Required when scope is 'employee'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_thresholds', to='users.employee')),
                ('manager', models.ForeignKey(blank=True, help_text="Required when scope is 'manager'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_thresholds', to='users.manager')),
            ],
            options={
                'verbose_name': 'Analytics Threshold',
                'verbose_name_plural': 'Analytics Thresholds',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope', 'is_active'], name='dashboard_a_scope_2352e4_idx')],
            },
        ),
    ]
