# Generated by Django 4.2.7 on 2026-02-15 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_analytics_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'Manually Triggered'), ('cron', 'Automated Cron Job')], default='cron', max_length=10)),
                ('status', models.CharField(choices=[('success', 'Successfully Sent'), ('failed', 'Failed to Send'), ('partial', 'Partially Failed')], default='success', max_length=10)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('total_doors', models.IntegerField(default=0)),
                ('unique_workers', models.IntegerField(default=0)),
                ('alerts_count', models.IntegerField(default=0)),
                ('critical_alerts_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('pdf_size_bytes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Report',
                'verbose_name_plural': 'Analytics Reports',
                'db_table': 'analytics_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='analytics_r_start_d_95b70f_idx'), models.Index(fields=['source', 'status'], name='analytics_r_source_683395_idx'), models.Index(fields=['sent_at'], name='analytics_r_sent_at_130f14_idx')],
            },
        ),
    ]
