# Generated by Django 4.2.7 on 2026-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_analytics_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsreport',
            name='recipient_email',
            field=models.CharField(help_text='Comma-separated list of recipient email addresses', max_length=500),
        ),
    ]
