# Generated by Django 4.2.7 on 2026-01-27 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAssignedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Task priority', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, help_text='Task deadline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Assigned Task',
                'verbose_name_plural': 'Admin Assigned Tasks',
                'db_table': 'admin_assigned_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_user_id_6c4bf2_idx',
            old_name='todo_user_id_f0c5da_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_user_id_886afe_idx',
            old_name='todo_user_id_336b8d_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_status_3d791b_idx',
            old_name='todo_status_b5b9c4_idx',
        ),
        migrations.AddField(
            model_name='adminassignedtask',
            name='created_by',
            field=models.ForeignKey(help_text='Admin user who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='admin_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned this task (if admin-assigned)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='admin_assigned_task',
            field=models.ForeignKey(blank=True, help_text='If set, this todo was assigned by an admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_todos', to='todos.adminassignedtask'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['admin_assigned_task', 'status'], name='todo_admin_a_882ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['assigned_by', 'created_at'], name='todo_assigne_870a54_idx'),
        ),
        migrations.AddIndex(
            model_name='adminassignedtask',
            index=models.Index(fields=['created_by', 'deadline'], name='admin_assig_created_757847_idx'),
        ),
        migrations.AddIndex(
            model_name='adminassignedtask',
            index=models.Index(fields=['created_at'], name='admin_assig_created_58d99c_idx'),
        ),
    ]
