# Generated by Django 4.2.7 on 2026-04-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0004_remove_admin_assigned_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todo',
            new_name='todo_user_id_68a9e8_idx',
            old_name='todo_user_is_admin_idx',
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this task (if assigned)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
