import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // shadcn / radix tokens (mapped to AB palette in globals.css)
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },

        // Generic role-named aliases (Linear/Vercel style) → AB tokens
        // These let new primitives use bg-surface / text-secondary etc.
        "surface":         "var(--ab-bg-elevated)",
        "surface-subtle":  "var(--ab-bg-subtle)",
        "border-strong":   "var(--ab-border-strong)",
        "text-primary":    "var(--ab-text-primary)",
        "text-secondary":  "var(--ab-text-secondary)",
        "text-tertiary":   "var(--ab-text-tertiary)",
        success:           "var(--ab-success-fg)",
        "success-bg":      "var(--ab-success-bg)",
        warning:           "var(--ab-warning-fg)",
        "warning-bg":      "var(--ab-warning-bg)",
        danger:            "var(--ab-danger-fg)",
        "danger-bg":       "var(--ab-danger-bg)",

        // AB design system tokens (use these in new components)
        ab: {
          canvas:    "var(--ab-bg-canvas)",
          base:      "var(--ab-bg-base)",
          subtle:    "var(--ab-bg-subtle)",
          elevated:  "var(--ab-bg-elevated)",
          overlay:   "var(--ab-bg-overlay)",
          hover:     "var(--ab-bg-hover)",
          active:    "var(--ab-bg-active)",
          inset:     "var(--ab-bg-inset)",
          fg:        "var(--ab-text-primary)",
          "fg-2":    "var(--ab-text-secondary)",
          "fg-3":    "var(--ab-text-tertiary)",
          "fg-4":    "var(--ab-text-quaternary)",
          "on-accent": "var(--ab-text-on-accent)",
          line:      "var(--ab-border-default)",
          "line-2":  "var(--ab-border-strong)",
          "line-1":  "var(--ab-border-subtle)",
          accent:    "var(--ab-accent-9)",
          "accent-2":"var(--ab-accent-10)",
          "accent-3":"var(--ab-accent-11)",
          "accent-soft": "var(--ab-accent-3)",
          navy:      "var(--ab-navy-9)",
          teal:      "var(--ab-teal-9)",
          success:   "var(--ab-success-fg)",
          "success-bg": "var(--ab-success-bg)",
          warning:   "var(--ab-warning-fg)",
          "warning-bg": "var(--ab-warning-bg)",
          danger:    "var(--ab-danger-fg)",
          "danger-bg": "var(--ab-danger-bg)",
          info:      "var(--ab-info-fg)",
          "info-bg": "var(--ab-info-bg)",
        },
        viz: {
          1: "var(--viz-1)",
          2: "var(--viz-2)",
          3: "var(--viz-3)",
          4: "var(--viz-4)",
          5: "var(--viz-5)",
          6: "var(--viz-6)",
          7: "var(--viz-7)",
          8: "var(--viz-8)",
          9: "var(--viz-9)",
          10: "var(--viz-10)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "ab-xs": "var(--radius-xs)",
        "ab-sm": "var(--radius-sm)",
        "ab-md": "var(--radius-md)",
        "ab-lg": "var(--radius-lg)",
        "ab-xl": "var(--radius-xl)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      transitionTimingFunction: {
        "out-quint": "var(--ease-out-quint)",
        "out-expo":  "var(--ease-out-expo)",
        "out-cubic": "var(--ease-out-cubic)",
        spring:      "var(--ease-spring)",
        "ios-sheet": "var(--ease-ios-sheet)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
        "ab-fade-in":      { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "ab-slide-up":     { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "ab-slide-in-right": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "ab-modal-in":     { "0%": { opacity: "0", transform: "translateY(24px) scale(0.94)" }, "100%": { opacity: "1", transform: "translateY(0) scale(1)" } },
        "ab-toast-in":     { "0%": { opacity: "0", transform: "translateX(40px) scale(0.96)" }, "100%": { opacity: "1", transform: "translateX(0) scale(1)" } },
        "ab-float-in":     { "0%": { opacity: "0", transform: "translateY(20px) scale(0.92)" }, "60%": { transform: "translateY(-4px) scale(1.02)" }, "100%": { opacity: "1", transform: "translateY(0) scale(1)" } },
        "ab-pulse-live":   { "0%": { boxShadow: "0 0 0 0 rgba(18,165,148,0.7)" }, "70%": { boxShadow: "0 0 0 6px rgba(18,165,148,0)" }, "100%": { boxShadow: "0 0 0 0 rgba(18,165,148,0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "ab-fade-in":     "ab-fade-in 200ms var(--ease-out-cubic) both",
        "ab-slide-up":    "ab-slide-up 500ms var(--ease-out-cubic) both",
        "ab-slide-in-right": "ab-slide-in-right 240ms var(--ease-ios-sheet) both",
        "ab-modal-in":    "ab-modal-in 320ms var(--ease-spring) both",
        "ab-toast-in":    "ab-toast-in 360ms var(--ease-out-cubic) both",
        "ab-float-in":    "ab-float-in 600ms var(--ease-spring) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
